--------------------------------------------------------
--  Database DDL for NSCC Application Form
--  Author: Ryan Sutcliffe (w0143446)
--  Created: February 10, 2016
--  Last Modified: February 19, 2016
--  DDL Created in SQL Developer and exported to DDL text
--------------------------------------------------------
	
--  DDL for Table CAMPUS
	CREATE TABLE "RYAN_DDL"."CAMPUS" 
	(	
	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50 BYTE)
	);

--  DDL for Table CITIZENSHIPLU
	CREATE TABLE "RYAN_DDL"."CITIZENSHIPLU" 
	(	
	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50 BYTE)
	);

--  DDL for Table COUNTRIESLU
	CREATE TABLE "RYAN_DDL"."COUNTRIESLU" 
	(	
	"CODE" CHAR(2 BYTE), 
	"NAME" VARCHAR2(75 BYTE)
	) ;

--  DDL for Table NSCOUNTIESLU
	CREATE TABLE "RYAN_DDL"."NSCOUNTIESLU" 
	(	
	"ID" INT, 
	"NAME" VARCHAR2(65 BYTE)
	);
--  DDL for Table PERSONALINFO
	CREATE TABLE "RYAN_DDL"."PERSONALINFO" 
	(	
	"APPLICATIONID" NUMBER(*,0), 
	"FNAME" VARCHAR2(50 BYTE), 
	"LNAME" VARCHAR2(50 BYTE), 
	"SIN" CHAR(9 BYTE), 
	"PLNAME" VARCHAR2(50 BYTE), 
	"BIRTHDATE" DATE, 
	"GENDER" CHAR(1 BYTE), 
	"APTNO" VARCHAR2(6 BYTE), 
	"ADDRESSLINE1" VARCHAR2(100 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	"COUNTY" NUMBER(*,0), 
	"PROV" CHAR(2 BYTE) DEFAULT 'NS', 
	"COUNTRY" CHAR(2 BYTE) DEFAULT 'CA', 
	"POSTALCODE" CHAR(6 BYTE), 
	"HPHONE" CHAR(10 BYTE), 
	"WPHONE" CHAR(10 BYTE), 
	"CPHONE" CHAR(10 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"STUDENTID" CHAR(7 BYTE), 
	"CITIZENSHIP" NUMBER(*,0) DEFAULT 1, 
	"ENGLISH" CHAR(1 BYTE) DEFAULT 'Y', 
	"OTHERCITIZENCOUNTRY" CHAR(2 BYTE), 
	"FIRSTLANG" VARCHAR2(50 BYTE), 
	"PROGRAM1" NUMBER(*,0), 
	"PROGRAM2" NUMBER(*,0), 
	"CAMPUS1" NUMBER(*,0), 
	"CAMPUS2" NUMBER(*,0), 
	"PAID" CHAR(1 BYTE) DEFAULT 'N'
	) ;

   COMMENT ON COLUMN "RYAN_DDL"."PERSONALINFO"."APPLICATIONID" IS 'Unique ID for Applicant. Needs to autoincrement';
   COMMENT ON COLUMN "RYAN_DDL"."PERSONALINFO"."FNAME" IS 'First Name';
   COMMENT ON COLUMN "RYAN_DDL"."PERSONALINFO"."LNAME" IS 'Last Name';
   COMMENT ON COLUMN "RYAN_DDL"."PERSONALINFO"."SIN" IS 'SIN number (needs rule to be numeric)';
   COMMENT ON COLUMN "RYAN_DDL"."PERSONALINFO"."PLNAME" IS 'Previous Last Name';
   COMMENT ON COLUMN "RYAN_DDL"."PERSONALINFO"."BIRTHDATE" IS 'Date of Birth';
   COMMENT ON COLUMN "RYAN_DDL"."PERSONALINFO"."GENDER" IS 'm/f/o (needs lookup)';
   COMMENT ON COLUMN "RYAN_DDL"."PERSONALINFO"."APTNO" IS 'Apt No (can be letter(s))';
   COMMENT ON COLUMN "RYAN_DDL"."PERSONALINFO"."ADDRESSLINE1" IS 'Address Street Info';
   

--  DDL for Table PROGRAM
	CREATE TABLE "RYAN_DDL"."PROGRAM" 
	(	
	"ID" NUMBER(*,0), 
	"PROGRAMNAME" VARCHAR2(50 BYTE)
	);

--  DDL for Table PROGRAMCAMPUSMAPPING
	CREATE TABLE "RYAN_DDL"."PROGRAMCAMPUSMAPPING" 
	(	
	"ID" NUMBER(*,0), 
	"PROGRAMID" NUMBER(*,0), 
	"CAMPUSID" NUMBER(*,0)
	) ;

--  DDL for Table PROVINCESLU
	CREATE TABLE "RYAN_DDL"."PROVINCESLU" 
	(		
	"CODE" CHAR(2 BYTE), 
	"NAME" VARCHAR2(50 BYTE)
	) ;

--  DDL for Index PERSONALINFO_PK
  CREATE UNIQUE INDEX "RYAN_DDL"."PERSONALINFO_PK" ON "RYAN_DDL"."PERSONALINFO" ("APPLICATIONID") ;
--  DDL for Index PROGRAM_PK
  CREATE UNIQUE INDEX "RYAN_DDL"."PROGRAM_PK" ON "RYAN_DDL"."PROGRAM" ("ID") ;
--  DDL for Index PROVINCESLU_PK
  CREATE UNIQUE INDEX "RYAN_DDL"."PROVINCESLU_PK" ON "RYAN_DDL"."PROVINCESLU" ("CODE"); 
--  DDL for Index CITIZENSHIPLU_PK
  CREATE UNIQUE INDEX "RYAN_DDL"."CITIZENSHIPLU_PK" ON "RYAN_DDL"."CITIZENSHIPLU" ("ID"); 
--  DDL for Index PROGRAMCAMPUSMAPPING_PK
  CREATE UNIQUE INDEX "RYAN_DDL"."PROGRAMCAMPUSMAPPING_PK" ON "RYAN_DDL"."PROGRAMCAMPUSMAPPING" ("ID"); 
--  DDL for Index COUNTRIESLU_PK
  CREATE UNIQUE INDEX "RYAN_DDL"."COUNTRIESLU_PK" ON "RYAN_DDL"."COUNTRIESLU" ("CODE") ;
--  DDL for Index CAMPUS_PK
  CREATE UNIQUE INDEX "RYAN_DDL"."CAMPUS_PK" ON "RYAN_DDL"."CAMPUS" ("ID") ;
--  DDL for Index NSCOUNTIESLU_PK
  CREATE UNIQUE INDEX "RYAN_DDL"."NSCOUNTIESLU_PK" ON "RYAN_DDL"."NSCOUNTIESLU" ("ID"); 

--  Constraints for Table NSCOUNTIESLU
  ALTER TABLE "RYAN_DDL"."NSCOUNTIESLU" ADD CONSTRAINT "NSCOUNTIESLU_PK" PRIMARY KEY ("ID");
  ALTER TABLE "RYAN_DDL"."NSCOUNTIESLU" MODIFY ("ID" NOT NULL ENABLE);
--  Constraints for Table CAMPUS
  ALTER TABLE "RYAN_DDL"."CAMPUS" ADD CONSTRAINT "CAMPUS_PK" PRIMARY KEY ("ID");
  ALTER TABLE "RYAN_DDL"."CAMPUS" MODIFY ("ID" NOT NULL ENABLE);
--  Constraints for Table PROGRAM
  ALTER TABLE "RYAN_DDL"."PROGRAM" ADD CONSTRAINT "PROGRAM_PK" PRIMARY KEY ("ID");
  ALTER TABLE "RYAN_DDL"."PROGRAM" MODIFY ("ID" NOT NULL ENABLE);
--  Constraints for Table PROVINCESLU
  ALTER TABLE "RYAN_DDL"."PROVINCESLU" ADD CONSTRAINT "PROVINCESLU_PK" PRIMARY KEY ("CODE");
  ALTER TABLE "RYAN_DDL"."PROVINCESLU" MODIFY ("CODE" NOT NULL ENABLE);
--  Constraints for Table PERSONALINFO
  ALTER TABLE "RYAN_DDL"."PERSONALINFO" MODIFY ("FNAME" NOT NULL ENABLE);
  ALTER TABLE "RYAN_DDL"."PERSONALINFO" MODIFY ("ENGLISH" NOT NULL ENABLE);
  ALTER TABLE "RYAN_DDL"."PERSONALINFO" MODIFY ("CITIZENSHIP" NOT NULL ENABLE);
  ALTER TABLE "RYAN_DDL"."PERSONALINFO" ADD CONSTRAINT "PERSONALINFO_PK" PRIMARY KEY ("APPLICATIONID");
  ALTER TABLE "RYAN_DDL"."PERSONALINFO" MODIFY ("BIRTHDATE" NOT NULL ENABLE);
  ALTER TABLE "RYAN_DDL"."PERSONALINFO" MODIFY ("LNAME" NOT NULL ENABLE);
  ALTER TABLE "RYAN_DDL"."PERSONALINFO" MODIFY ("APPLICATIONID" NOT NULL ENABLE);
--  Constraints for Table COUNTRIESLU
  ALTER TABLE "RYAN_DDL"."COUNTRIESLU" ADD CONSTRAINT "COUNTRIESLU_PK" PRIMARY KEY ("CODE");
  ALTER TABLE "RYAN_DDL"."COUNTRIESLU" MODIFY ("CODE" NOT NULL ENABLE);
--  Constraints for Table PROGRAMCAMPUSMAPPING
  ALTER TABLE "RYAN_DDL"."PROGRAMCAMPUSMAPPING" ADD CONSTRAINT "PROGRAMCAMPUSMAPPING_PK" PRIMARY KEY ("ID");
  ALTER TABLE "RYAN_DDL"."PROGRAMCAMPUSMAPPING" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RYAN_DDL"."PROGRAMCAMPUSMAPPING" MODIFY ("CAMPUSID" NOT NULL ENABLE);
  ALTER TABLE "RYAN_DDL"."PROGRAMCAMPUSMAPPING" MODIFY ("PROGRAMID" NOT NULL ENABLE);
--  Constraints for Table CITIZENSHIPLU
  ALTER TABLE "RYAN_DDL"."CITIZENSHIPLU" ADD CONSTRAINT "CITIZENSHIPLU_PK" PRIMARY KEY ("ID");
  ALTER TABLE "RYAN_DDL"."CITIZENSHIPLU" MODIFY ("ID" NOT NULL ENABLE);

--  Ref Constraints for Table PERSONALINFO
  ALTER TABLE "RYAN_DDL"."PERSONALINFO" ADD CONSTRAINT "FK_CAMPUS1" FOREIGN KEY ("CAMPUS1")
	  REFERENCES "RYAN_DDL"."CAMPUS" ("ID") ENABLE;
  ALTER TABLE "RYAN_DDL"."PERSONALINFO" ADD CONSTRAINT "FK_CAMPUS2" FOREIGN KEY ("CAMPUS2")
	  REFERENCES "RYAN_DDL"."CAMPUS" ("ID") ENABLE;
  ALTER TABLE "RYAN_DDL"."PERSONALINFO" ADD CONSTRAINT "FK_COUNTRY" FOREIGN KEY ("COUNTRY")
	  REFERENCES "RYAN_DDL"."COUNTRIESLU" ("CODE") ENABLE;
  ALTER TABLE "RYAN_DDL"."PERSONALINFO" ADD CONSTRAINT "FK_COUNTY" FOREIGN KEY ("COUNTY")
	  REFERENCES "RYAN_DDL"."NSCOUNTIESLU" ("ID") ENABLE;
  ALTER TABLE "RYAN_DDL"."PERSONALINFO" ADD CONSTRAINT "FK_PROVINCE" FOREIGN KEY ("PROV")
	  REFERENCES "RYAN_DDL"."PROVINCESLU" ("CODE") ENABLE;
  ALTER TABLE "RYAN_DDL"."PERSONALINFO" ADD CONSTRAINT "PERSONALINFO_CITIZENSHIP_FK" FOREIGN KEY ("CITIZENSHIP")
	  REFERENCES "RYAN_DDL"."CITIZENSHIPLU" ("ID") ENABLE;
  ALTER TABLE "RYAN_DDL"."PERSONALINFO" ADD CONSTRAINT "PERSONALINFO_OTHERCITIZENCO_FK" FOREIGN KEY ("OTHERCITIZENCOUNTRY")
	  REFERENCES "RYAN_DDL"."COUNTRIESLU" ("CODE") ENABLE;
  ALTER TABLE "RYAN_DDL"."PERSONALINFO" ADD CONSTRAINT "PERSONALINFO_PROGRAM2_FK" FOREIGN KEY ("PROGRAM2")
	  REFERENCES "RYAN_DDL"."PROGRAM" ("ID") ENABLE;
  ALTER TABLE "RYAN_DDL"."PERSONALINFO" ADD CONSTRAINT "PERSONALINFO_PROGRAM_FK" FOREIGN KEY ("PROGRAM1")
	  REFERENCES "RYAN_DDL"."PROGRAM" ("ID") ENABLE;
--  Ref Constraints for Table PROGRAMCAMPUSMAPPING
  ALTER TABLE "RYAN_DDL"."PROGRAMCAMPUSMAPPING" ADD CONSTRAINT "FK_CAMPUS" FOREIGN KEY ("CAMPUSID")
	  REFERENCES "RYAN_DDL"."CAMPUS" ("ID") ENABLE;
  ALTER TABLE "RYAN_DDL"."PROGRAMCAMPUSMAPPING" ADD CONSTRAINT "FK_PROGRAM" FOREIGN KEY ("PROGRAMID")
	  REFERENCES "RYAN_DDL"."PROGRAM" ("ID") ENABLE;


--  DDL for Trigger TR_PERSONALINFO_APPID_BI
CREATE OR REPLACE TRIGGER "RYAN_DDL"."TR_PERSONALINFO_APPID_BI" -- bi = before insert 
BEFORE INSERT ON personalinfo 
FOR EACH ROW
 WHEN (new.applicationid IS NULL) BEGIN
  SELECT PERSONALINFO_APPLICATIONID_SEQ.NEXTVAL
  INTO   :new.applicationid
  FROM   dual;
END;
/
ALTER TRIGGER "RYAN_DDL"."TR_PERSONALINFO_APPID_BI" ENABLE;


--  DDL for Trigger TR_PERSONALINFO_APPID_BI
CREATE OR REPLACE TRIGGER "RYAN_DDL"."TR_PROGRAM_ID_BI" -- bi = before insert 
BEFORE INSERT ON program 
FOR EACH ROW
 WHEN (new.id IS NULL) BEGIN
  SELECT PROGRAM_SEQ.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/
ALTER TRIGGER "RYAN_DDL"."TR_PROGRAM_ID_BI" ENABLE;


--  DDL for Trigger TR_CAMPUSID_BI
CREATE OR REPLACE TRIGGER "RYAN_DDL"."TR_CAMPUSID_BI" -- bi = before insert 
BEFORE INSERT ON campus 
FOR EACH ROW
 WHEN (new.id IS NULL) BEGIN
  SELECT campusid_SEQ.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/
ALTER TRIGGER "RYAN_DDL"."TR_CAMPUSID_BI" ENABLE;


-- Create Sequences
CREATE SEQUENCE  "RYAN_DDL"."CAMPUSID_SEQ"  
MINVALUE 1 
MAXVALUE 500
INCREMENT BY 1 
START WITH 1 
CACHE 50
NOORDER  
NOCYCLE;


-- Create Sequences
CREATE SEQUENCE  "RYAN_DDL"."PROGRAM_SEQ"  
MINVALUE 1 
MAXVALUE 500
INCREMENT BY 1 
START WITH 1 
CACHE 50
NOORDER  
NOCYCLE;



CREATE SEQUENCE  "RYAN_DDL"."NSCOUNTIESLU_SEQ"  
MINVALUE 1 
MAXVALUE 99999
INCREMENT BY 1 
START WITH 1 
CACHE 20 
NOORDER  
NOCYCLE;

CREATE SEQUENCE  "RYAN_DDL"."PERSONALINFO_APPLICATIONID_SEQ"  
MINVALUE 1 
MAXVALUE 99999
INCREMENT BY 1 
START WITH 1 
CACHE 20 
NOORDER  
NOCYCLE;

