--------------------------------------------------------
--  Database DDL for NSCC Application Form
--  Author: Ryan Sutcliffe (w0143446)
--  Created: February 10, 2016
--  Last Modified: February 19, 2016
--  DDL Created in SQL Developer and exported to DDL text
--  Revision notes: This version updated with slight table tweaks and changes
--  All edits can be tracked on GitHub here: https://github.com/ryansutc/NSCCApplicationDatabase
--------------------------------------------------------
	
--  DDL for Table CAMPUS
	CREATE TABLE CAMPUS 
	(	
	ID INT, 
	NAME VARCHAR2(50)
	);

--  DDL for Table CITIZENSHIPLU
	CREATE TABLE CITIZENSHIPLU 
	(	
	ID INT, 
	NAME VARCHAR2(50 BYTE)
	);

--  DDL for Table COUNTRIESLU
	CREATE TABLE COUNTRIESLU 
	(	
	CODE CHAR(2 BYTE), 
	NAME VARCHAR2(75 BYTE)
	) ;

--  DDL for Table NSCOUNTIESLU
	CREATE TABLE NSCOUNTIESLU 
	(	
	ID INT, 
	NAME VARCHAR2(65 BYTE)
	);
--  DDL for Table PERSONALINFO
	CREATE TABLE PERSONALINFO 
	(	
	APPLICATIONID INT, 
	FNAME VARCHAR2(50 BYTE), 
	LNAME VARCHAR2(50 BYTE), 
	SIN CHAR(9 BYTE), 
	PLNAME VARCHAR2(50 BYTE), 
	BIRTHDATE DATE, 
	GENDER CHAR(1 BYTE), 
	APTNO VARCHAR2(6 BYTE), 
	ADDRESSLINE1 VARCHAR2(100 BYTE), 
	CITY VARCHAR2(50 BYTE), 
	COUNTY INT, 
	PROV CHAR(2 BYTE) DEFAULT 'NS', 
	COUNTRY CHAR(2 BYTE) DEFAULT 'CA', 
	POSTALCODE CHAR(6 BYTE), 
	HPHONE CHAR(10 BYTE), 
	WPHONE CHAR(10 BYTE), 
	CPHONE CHAR(10 BYTE), 
	EMAIL VARCHAR2(50 BYTE), 
	STUDENTID CHAR(7 BYTE), 
	CITIZENSHIP INT DEFAULT 1, 
	ENGLISH CHAR(1 BYTE) DEFAULT 'Y', 
	OTHERCITIZENCOUNTRY CHAR(2 BYTE), 
	FIRSTLANG VARCHAR2(50 BYTE), 
	PROGRAM1 INT, 
	PROGRAM2 INT, 
	CAMPUS1 INT, 
	CAMPUS2 INT, 
	PAID CHAR(1 BYTE) DEFAULT 'N'
	) ;

   COMMENT ON COLUMN PERSONALINFO.APPLICATIONID IS 'Unique ID for Applicant. Needs to autoincrement';
   COMMENT ON COLUMN PERSONALINFO.FNAME IS 'First Name';
   COMMENT ON COLUMN PERSONALINFO.LNAME IS 'Last Name';
   COMMENT ON COLUMN PERSONALINFO.SIN IS 'SIN number (needs rule to be numeric)';
   COMMENT ON COLUMN PERSONALINFO.PLNAME IS 'Previous Last Name';
   COMMENT ON COLUMN PERSONALINFO.BIRTHDATE IS 'Date of Birth';
   COMMENT ON COLUMN PERSONALINFO.GENDER IS 'm/f/o (needs lookup)';
   COMMENT ON COLUMN PERSONALINFO.APTNO IS 'Apt No (can be letter(s))';
   COMMENT ON COLUMN PERSONALINFO.ADDRESSLINE1 IS 'Address Street Info';
   

--  DDL for Table PROGRAM
	CREATE TABLE PROGRAM 
	(	
	ID INT, 
	PROGRAMNAME VARCHAR2(50 BYTE)
	);

--  DDL for Table PROGRAMCAMPUSMAPPING
	CREATE TABLE PROGRAMCAMPUSMAPPING 
	(	
	ID INT, 
	PROGRAMID INT, 
	CAMPUSID INT
	) ;

--  DDL for Table PROVINCESLU
	CREATE TABLE PROVINCESLU 
	(		
	CODE CHAR(2 BYTE), 
	NAME VARCHAR2(50 BYTE)
	) ;

--  DDL for Index PERSONALINFO_PK
  CREATE UNIQUE INDEX PERSONALINFO_PK ON PERSONALINFO (APPLICATIONID) ;
--  DDL for Index PROGRAM_PK
  CREATE UNIQUE INDEX PROGRAM_PK ON PROGRAM (ID) ;
--  DDL for Index PROVINCESLU_PK
  CREATE UNIQUE INDEX PROVINCESLU_PK ON PROVINCESLU (CODE); 
--  DDL for Index CITIZENSHIPLU_PK
  CREATE UNIQUE INDEX CITIZENSHIPLU_PK ON CITIZENSHIPLU (ID); 
--  DDL for Index PROGRAMCAMPUSMAPPING_PK
  CREATE UNIQUE INDEX PROGRAMCAMPUSMAPPING_PK ON PROGRAMCAMPUSMAPPING (ID); 
--  DDL for Index COUNTRIESLU_PK
  CREATE UNIQUE INDEX COUNTRIESLU_PK ON COUNTRIESLU (CODE) ;
--  DDL for Index CAMPUS_PK
  CREATE UNIQUE INDEX CAMPUS_PK ON CAMPUS (ID) ;
--  DDL for Index NSCOUNTIESLU_PK
  CREATE UNIQUE INDEX NSCOUNTIESLU_PK ON NSCOUNTIESLU (ID); 

--  Constraints for Table NSCOUNTIESLU
  ALTER TABLE NSCOUNTIESLU ADD CONSTRAINT NSCOUNTIESLU_PK PRIMARY KEY (ID);
  ALTER TABLE NSCOUNTIESLU MODIFY (ID NOT NULL ENABLE);
--  Constraints for Table CAMPUS
  ALTER TABLE CAMPUS ADD CONSTRAINT CAMPUS_PK PRIMARY KEY (ID);
  ALTER TABLE CAMPUS MODIFY (ID NOT NULL ENABLE);
--  Constraints for Table PROGRAM
  ALTER TABLE PROGRAM ADD CONSTRAINT PROGRAM_PK PRIMARY KEY (ID);
  ALTER TABLE PROGRAM MODIFY (ID NOT NULL ENABLE);
--  Constraints for Table PROVINCESLU
  ALTER TABLE PROVINCESLU ADD CONSTRAINT PROVINCESLU_PK PRIMARY KEY (CODE);
  ALTER TABLE PROVINCESLU MODIFY (CODE NOT NULL ENABLE);
--  Constraints for Table PERSONALINFO
  ALTER TABLE PERSONALINFO MODIFY (FNAME NOT NULL ENABLE);
  ALTER TABLE PERSONALINFO MODIFY (ENGLISH NOT NULL ENABLE);
  ALTER TABLE PERSONALINFO MODIFY (CITIZENSHIP NOT NULL ENABLE);
  ALTER TABLE PERSONALINFO ADD CONSTRAINT PERSONALINFO_PK PRIMARY KEY (APPLICATIONID);
  ALTER TABLE PERSONALINFO MODIFY (BIRTHDATE NOT NULL ENABLE);
  ALTER TABLE PERSONALINFO MODIFY (LNAME NOT NULL ENABLE);
  ALTER TABLE PERSONALINFO MODIFY (APPLICATIONID NOT NULL ENABLE);
--  Constraints for Table COUNTRIESLU
  ALTER TABLE COUNTRIESLU ADD CONSTRAINT COUNTRIESLU_PK PRIMARY KEY (CODE);
  ALTER TABLE COUNTRIESLU MODIFY (CODE NOT NULL ENABLE);
--  Constraints for Table PROGRAMCAMPUSMAPPING
  ALTER TABLE PROGRAMCAMPUSMAPPING ADD CONSTRAINT PROGRAMCAMPUSMAPPING_PK PRIMARY KEY (ID);
  ALTER TABLE PROGRAMCAMPUSMAPPING MODIFY (ID NOT NULL ENABLE);
  ALTER TABLE PROGRAMCAMPUSMAPPING MODIFY (CAMPUSID NOT NULL ENABLE);
  ALTER TABLE PROGRAMCAMPUSMAPPING MODIFY (PROGRAMID NOT NULL ENABLE);
--  Constraints for Table CITIZENSHIPLU
  ALTER TABLE CITIZENSHIPLU ADD CONSTRAINT CITIZENSHIPLU_PK PRIMARY KEY (ID);
  ALTER TABLE CITIZENSHIPLU MODIFY (ID NOT NULL ENABLE);

--  Ref Constraints for Table PERSONALINFO
  ALTER TABLE PERSONALINFO ADD CONSTRAINT FK_CAMPUS1 FOREIGN KEY (CAMPUS1)
	  REFERENCES CAMPUS (ID) ENABLE;
  ALTER TABLE PERSONALINFO ADD CONSTRAINT FK_CAMPUS2 FOREIGN KEY (CAMPUS2)
	  REFERENCES CAMPUS (ID) ENABLE;
  ALTER TABLE PERSONALINFO ADD CONSTRAINT FK_COUNTRY FOREIGN KEY (COUNTRY)
	  REFERENCES COUNTRIESLU (CODE) ENABLE;
  ALTER TABLE PERSONALINFO ADD CONSTRAINT FK_COUNTY FOREIGN KEY (COUNTY)
	  REFERENCES NSCOUNTIESLU (ID) ENABLE;
  ALTER TABLE PERSONALINFO ADD CONSTRAINT FK_PROVINCE FOREIGN KEY (PROV)
	  REFERENCES PROVINCESLU (CODE) ENABLE;
  ALTER TABLE PERSONALINFO ADD CONSTRAINT PERSONALINFO_CITIZENSHIP_FK FOREIGN KEY (CITIZENSHIP)
	  REFERENCES CITIZENSHIPLU (ID) ENABLE;
  ALTER TABLE PERSONALINFO ADD CONSTRAINT PERSONALINFO_OTHERCITIZENCO_FK FOREIGN KEY (OTHERCITIZENCOUNTRY)
	  REFERENCES COUNTRIESLU (CODE) ENABLE;
  ALTER TABLE PERSONALINFO ADD CONSTRAINT PERSONALINFO_PROGRAM2_FK FOREIGN KEY (PROGRAM2)
	  REFERENCES PROGRAM (ID) ENABLE;
  ALTER TABLE PERSONALINFO ADD CONSTRAINT PERSONALINFO_PROGRAM_FK FOREIGN KEY (PROGRAM1)
	  REFERENCES PROGRAM (ID) ENABLE;
--  Ref Constraints for Table PROGRAMCAMPUSMAPPING
  ALTER TABLE PROGRAMCAMPUSMAPPING ADD CONSTRAINT FK_CAMPUS FOREIGN KEY (CAMPUSID)
	  REFERENCES CAMPUS (ID) ENABLE;
  ALTER TABLE PROGRAMCAMPUSMAPPING ADD CONSTRAINT FK_PROGRAM FOREIGN KEY (PROGRAMID)
	  REFERENCES PROGRAM (ID) ENABLE;


--  DDL for Trigger TR_PERSONALINFO_APPID_BI
CREATE OR REPLACE TRIGGER TR_PERSONALINFO_APPID_BI -- bi = before insert 
BEFORE INSERT ON personalinfo 
FOR EACH ROW
 WHEN (new.applicationid IS NULL) BEGIN
  SELECT PERSONALINFO_APPLICATIONID_SEQ.NEXTVAL
  INTO   :new.applicationid
  FROM   dual;
END;
/
ALTER TRIGGER TR_PERSONALINFO_APPID_BI ENABLE;


--  DDL for Trigger TR_PERSONALINFO_APPID_BI
CREATE OR REPLACE TRIGGER TR_PROGRAM_ID_BI -- bi = before insert 
BEFORE INSERT ON program 
FOR EACH ROW
 WHEN (new.id IS NULL) BEGIN
  SELECT PROGRAM_SEQ.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/
ALTER TRIGGER TR_PROGRAM_ID_BI ENABLE;


--  DDL for Trigger TR_CAMPUSID_BI
CREATE OR REPLACE TRIGGER TR_CAMPUSID_BI -- bi = before insert 
BEFORE INSERT ON campus 
FOR EACH ROW
 WHEN (new.id IS NULL) BEGIN
  SELECT campusid_SEQ.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/
ALTER TRIGGER TR_CAMPUSID_BI ENABLE;


-- Create Sequences
CREATE SEQUENCE  CAMPUSID_SEQ  
MINVALUE 1 
MAXVALUE 500
INCREMENT BY 1 
START WITH 1 
CACHE 50
NOORDER  
NOCYCLE;


-- Create Sequences
CREATE SEQUENCE  PROGRAM_SEQ  
MINVALUE 1 
MAXVALUE 500
INCREMENT BY 1 
START WITH 1 
CACHE 50
NOORDER  
NOCYCLE;



CREATE SEQUENCE  NSCOUNTIESLU_SEQ  
MINVALUE 1 
MAXVALUE 99999
INCREMENT BY 1 
START WITH 1 
CACHE 20 
NOORDER  
NOCYCLE;

CREATE SEQUENCE  PERSONALINFO_APPLICATIONID_SEQ  
MINVALUE 1 
MAXVALUE 99999
INCREMENT BY 1 
START WITH 1 
CACHE 20 
NOORDER  
NOCYCLE;

