--------------------------------------------------------
--  Database DML for NSCC Application Form
--  Author: Ryan Sutcliffe (w0143446)
--  Created: February 10, 2016
--  Last Modified: February 19, 2016
--  DML Created in SQL Developer and exported to DML text
--------------------------------------------------------



--Create Countries lookup table (List from here: https://github.com/raramuridesign/mysql-country-list/blob/master/mysql-country-list.sql)
INSERT INTO countrieslu VALUES ('AF', 'Afghanistan');
INSERT INTO countrieslu VALUES ('AL', 'Albania');
INSERT INTO countrieslu VALUES ('DZ', 'Algeria');
INSERT INTO countrieslu VALUES ('DS', 'American Samoa');
INSERT INTO countrieslu VALUES ('AD', 'Andorra');
INSERT INTO countrieslu VALUES ('AO', 'Angola');
INSERT INTO countrieslu VALUES ('AI', 'Anguilla');
INSERT INTO countrieslu VALUES ('AQ', 'Antarctica');
INSERT INTO countrieslu VALUES ('AG', 'Antigua and Barbuda');
INSERT INTO countrieslu VALUES ('AR', 'Argentina');
INSERT INTO countrieslu VALUES ('AM', 'Armenia');
INSERT INTO countrieslu VALUES ('AW', 'Aruba');
INSERT INTO countrieslu VALUES ('AU', 'Australia');
INSERT INTO countrieslu VALUES ('AT', 'Austria');
INSERT INTO countrieslu VALUES ('AZ', 'Azerbaijan');
INSERT INTO countrieslu VALUES ('BS', 'Bahamas');
INSERT INTO countrieslu VALUES ('BH', 'Bahrain');
INSERT INTO countrieslu VALUES ('BD', 'Bangladesh');
INSERT INTO countrieslu VALUES ('BB', 'Barbados');
INSERT INTO countrieslu VALUES ('BY', 'Belarus');
INSERT INTO countrieslu VALUES ('BE', 'Belgium');
INSERT INTO countrieslu VALUES ('BZ', 'Belize');
INSERT INTO countrieslu VALUES ('BJ', 'Benin');
INSERT INTO countrieslu VALUES ('BM', 'Bermuda');
INSERT INTO countrieslu VALUES ('BT', 'Bhutan');
INSERT INTO countrieslu VALUES ('BO', 'Bolivia');
INSERT INTO countrieslu VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO countrieslu VALUES ('BW', 'Botswana');
INSERT INTO countrieslu VALUES ('BV', 'Bouvet Island');
INSERT INTO countrieslu VALUES ('BR', 'Brazil');
INSERT INTO countrieslu VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO countrieslu VALUES ('BN', 'Brunei Darussalam');
INSERT INTO countrieslu VALUES ('BG', 'Bulgaria');
INSERT INTO countrieslu VALUES ('BF', 'Burkina Faso');
INSERT INTO countrieslu VALUES ('BI', 'Burundi');
INSERT INTO countrieslu VALUES ('KH', 'Cambodia');
INSERT INTO countrieslu VALUES ('CM', 'Cameroon');
INSERT INTO countrieslu VALUES ('CA', 'Canada');
INSERT INTO countrieslu VALUES ('CV', 'Cape Verde');
INSERT INTO countrieslu VALUES ('KY', 'Cayman Islands');
INSERT INTO countrieslu VALUES ('CF', 'Central African Republic');
INSERT INTO countrieslu VALUES ('TD', 'Chad');
INSERT INTO countrieslu VALUES ('CL', 'Chile');
INSERT INTO countrieslu VALUES ('CN', 'China');
INSERT INTO countrieslu VALUES ('CX', 'Christmas Island');
INSERT INTO countrieslu VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT INTO countrieslu VALUES ('CO', 'Colombia');
INSERT INTO countrieslu VALUES ('KM', 'Comoros');
INSERT INTO countrieslu VALUES ('CG', 'Congo');
INSERT INTO countrieslu VALUES ('CK', 'Cook Islands');
INSERT INTO countrieslu VALUES ('CR', 'Costa Rica');
INSERT INTO countrieslu VALUES ('HR', 'Croatia (Hrvatska)');
INSERT INTO countrieslu VALUES ('CU', 'Cuba');
INSERT INTO countrieslu VALUES ('CY', 'Cyprus');
INSERT INTO countrieslu VALUES ('CZ', 'Czech Republic');
INSERT INTO countrieslu VALUES ('DK', 'Denmark');
INSERT INTO countrieslu VALUES ('DJ', 'Djibouti');
INSERT INTO countrieslu VALUES ('DM', 'Dominica');
INSERT INTO countrieslu VALUES ('DO', 'Dominican Republic');
INSERT INTO countrieslu VALUES ('TP', 'East Timor');
INSERT INTO countrieslu VALUES ('EC', 'Ecuador');
INSERT INTO countrieslu VALUES ('EG', 'Egypt');
INSERT INTO countrieslu VALUES ('SV', 'El Salvador');
INSERT INTO countrieslu VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO countrieslu VALUES ('ER', 'Eritrea');
INSERT INTO countrieslu VALUES ('EE', 'Estonia');
INSERT INTO countrieslu VALUES ('ET', 'Ethiopia');
INSERT INTO countrieslu VALUES ('FK', 'Falkland Islands (Malvinas)');
INSERT INTO countrieslu VALUES ('FO', 'Faroe Islands');
INSERT INTO countrieslu VALUES ('FJ', 'Fiji');
INSERT INTO countrieslu VALUES ('FI', 'Finland');
INSERT INTO countrieslu VALUES ('FR', 'France');
INSERT INTO countrieslu VALUES ('FX', 'France, Metropolitan');
INSERT INTO countrieslu VALUES ('GF', 'French Guiana');
INSERT INTO countrieslu VALUES ('PF', 'French Polynesia');
INSERT INTO countrieslu VALUES ('TF', 'French Southern Territories');
INSERT INTO countrieslu VALUES ('GA', 'Gabon');
INSERT INTO countrieslu VALUES ('GM', 'Gambia');
INSERT INTO countrieslu VALUES ('GE', 'Georgia');
INSERT INTO countrieslu VALUES ('DE', 'Germany');
INSERT INTO countrieslu VALUES ('GH', 'Ghana');
INSERT INTO countrieslu VALUES ('GI', 'Gibraltar');
INSERT INTO countrieslu VALUES ('GK', 'Guernsey');
INSERT INTO countrieslu VALUES ('GR', 'Greece');
INSERT INTO countrieslu VALUES ('GL', 'Greenland');
INSERT INTO countrieslu VALUES ('GD', 'Grenada');
INSERT INTO countrieslu VALUES ('GP', 'Guadeloupe');
INSERT INTO countrieslu VALUES ('GU', 'Guam');
INSERT INTO countrieslu VALUES ('GT', 'Guatemala');
INSERT INTO countrieslu VALUES ('GN', 'Guinea');
INSERT INTO countrieslu VALUES ('GW', 'Guinea-Bissau');
INSERT INTO countrieslu VALUES ('GY', 'Guyana');
INSERT INTO countrieslu VALUES ('HT', 'Haiti');
INSERT INTO countrieslu VALUES ('HM', 'Heard and Mc Donald Islands');
INSERT INTO countrieslu VALUES ('HN', 'Honduras');
INSERT INTO countrieslu VALUES ('HK', 'Hong Kong');
INSERT INTO countrieslu VALUES ('HU', 'Hungary');
INSERT INTO countrieslu VALUES ('IS', 'Iceland');
INSERT INTO countrieslu VALUES ('IN', 'India');
INSERT INTO countrieslu VALUES ('IM', 'Isle of Man');
INSERT INTO countrieslu VALUES ('ID', 'Indonesia');
INSERT INTO countrieslu VALUES ('IR', 'Iran (Islamic Republic of)');
INSERT INTO countrieslu VALUES ('IQ', 'Iraq');
INSERT INTO countrieslu VALUES ('IE', 'Ireland');
INSERT INTO countrieslu VALUES ('IL', 'Israel');
INSERT INTO countrieslu VALUES ('IT', 'Italy');
INSERT INTO countrieslu VALUES ('CI', 'Ivory Coast');
INSERT INTO countrieslu VALUES ('JE', 'Jersey');
INSERT INTO countrieslu VALUES ('JM', 'Jamaica');
INSERT INTO countrieslu VALUES ('JP', 'Japan');
INSERT INTO countrieslu VALUES ('JO', 'Jordan');
INSERT INTO countrieslu VALUES ('KZ', 'Kazakhstan');
INSERT INTO countrieslu VALUES ('KE', 'Kenya');
INSERT INTO countrieslu VALUES ('KI', 'Kiribati');
INSERT INTO countrieslu VALUES ('KP', 'Korea, Democratic People''s Republic of');
INSERT INTO countrieslu VALUES ('KR', 'Korea, Republic of');
INSERT INTO countrieslu VALUES ('XK', 'Kosovo');
INSERT INTO countrieslu VALUES ('KW', 'Kuwait');
INSERT INTO countrieslu VALUES ('KG', 'Kyrgyzstan');
INSERT INTO countrieslu VALUES ('LA', 'Lao People''s Democratic Republic');
INSERT INTO countrieslu VALUES ('LV', 'Latvia');
INSERT INTO countrieslu VALUES ('LB', 'Lebanon');
INSERT INTO countrieslu VALUES ('LS', 'Lesotho');
INSERT INTO countrieslu VALUES ('LR', 'Liberia');
INSERT INTO countrieslu VALUES ('LY', 'Libyan Arab Jamahiriya');
INSERT INTO countrieslu VALUES ('LI', 'Liechtenstein');
INSERT INTO countrieslu VALUES ('LT', 'Lithuania');
INSERT INTO countrieslu VALUES ('LU', 'Luxembourg');
INSERT INTO countrieslu VALUES ('MO', 'Macau');
INSERT INTO countrieslu VALUES ('MK', 'Macedonia');
INSERT INTO countrieslu VALUES ('MG', 'Madagascar');
INSERT INTO countrieslu VALUES ('MW', 'Malawi');
INSERT INTO countrieslu VALUES ('MY', 'Malaysia');
INSERT INTO countrieslu VALUES ('MV', 'Maldives');
INSERT INTO countrieslu VALUES ('ML', 'Mali');
INSERT INTO countrieslu VALUES ('MT', 'Malta');
INSERT INTO countrieslu VALUES ('MH', 'Marshall Islands');
INSERT INTO countrieslu VALUES ('MQ', 'Martinique');
INSERT INTO countrieslu VALUES ('MR', 'Mauritania');
INSERT INTO countrieslu VALUES ('MU', 'Mauritius');
INSERT INTO countrieslu VALUES ('TY', 'Mayotte');
INSERT INTO countrieslu VALUES ('MX', 'Mexico');
INSERT INTO countrieslu VALUES ('FM', 'Micronesia, Federated States of');
INSERT INTO countrieslu VALUES ('MD', 'Moldova, Republic of');
INSERT INTO countrieslu VALUES ('MC', 'Monaco');
INSERT INTO countrieslu VALUES ('MN', 'Mongolia');
INSERT INTO countrieslu VALUES ('ME', 'Montenegro');
INSERT INTO countrieslu VALUES ('MS', 'Montserrat');
INSERT INTO countrieslu VALUES ('MA', 'Morocco');
INSERT INTO countrieslu VALUES ('MZ', 'Mozambique');
INSERT INTO countrieslu VALUES ('MM', 'Myanmar');
INSERT INTO countrieslu VALUES ('NA', 'Namibia');
INSERT INTO countrieslu VALUES ('NR', 'Nauru');
INSERT INTO countrieslu VALUES ('NP', 'Nepal');
INSERT INTO countrieslu VALUES ('NL', 'Netherlands');
INSERT INTO countrieslu VALUES ('AN', 'Netherlands Antilles');
INSERT INTO countrieslu VALUES ('NC', 'New Caledonia');
INSERT INTO countrieslu VALUES ('NZ', 'New Zealand');
INSERT INTO countrieslu VALUES ('NI', 'Nicaragua');
INSERT INTO countrieslu VALUES ('NE', 'Niger');
INSERT INTO countrieslu VALUES ('NG', 'Nigeria');
INSERT INTO countrieslu VALUES ('NU', 'Niue');
INSERT INTO countrieslu VALUES ('NF', 'Norfolk Island');
INSERT INTO countrieslu VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO countrieslu VALUES ('NO', 'Norway');
INSERT INTO countrieslu VALUES ('OM', 'Oman');
INSERT INTO countrieslu VALUES ('PK', 'Pakistan');
INSERT INTO countrieslu VALUES ('PW', 'Palau');
INSERT INTO countrieslu VALUES ('PS', 'Palestine');
INSERT INTO countrieslu VALUES ('PA', 'Panama');
INSERT INTO countrieslu VALUES ('PG', 'Papua New Guinea');
INSERT INTO countrieslu VALUES ('PY', 'Paraguay');
INSERT INTO countrieslu VALUES ('PE', 'Peru');
INSERT INTO countrieslu VALUES ('PH', 'Philippines');
INSERT INTO countrieslu VALUES ('PN', 'Pitcairn');
INSERT INTO countrieslu VALUES ('PL', 'Poland');
INSERT INTO countrieslu VALUES ('PT', 'Portugal');
INSERT INTO countrieslu VALUES ('PR', 'Puerto Rico');
INSERT INTO countrieslu VALUES ('QA', 'Qatar');
INSERT INTO countrieslu VALUES ('RE', 'Reunion');
INSERT INTO countrieslu VALUES ('RO', 'Romania');
INSERT INTO countrieslu VALUES ('RU', 'Russian Federation');
INSERT INTO countrieslu VALUES ('RW', 'Rwanda');
INSERT INTO countrieslu VALUES ('KN', 'Saint Kitts and Nevis');
INSERT INTO countrieslu VALUES ('LC', 'Saint Lucia');
INSERT INTO countrieslu VALUES ('VC', 'Saint Vincent and the Grenadines');
INSERT INTO countrieslu VALUES ('WS', 'Samoa');
INSERT INTO countrieslu VALUES ('SM', 'San Marino');
INSERT INTO countrieslu VALUES ('ST', 'Sao Tome and Principe');
INSERT INTO countrieslu VALUES ('SA', 'Saudi Arabia');
INSERT INTO countrieslu VALUES ('SN', 'Senegal');
INSERT INTO countrieslu VALUES ('RS', 'Serbia');
INSERT INTO countrieslu VALUES ('SC', 'Seychelles');
INSERT INTO countrieslu VALUES ('SL', 'Sierra Leone');
INSERT INTO countrieslu VALUES ('SG', 'Singapore');
INSERT INTO countrieslu VALUES ('SK', 'Slovakia');
INSERT INTO countrieslu VALUES ('SI', 'Slovenia');
INSERT INTO countrieslu VALUES ('SB', 'Solomon Islands');
INSERT INTO countrieslu VALUES ('SO', 'Somalia');
INSERT INTO countrieslu VALUES ('ZA', 'South Africa');
INSERT INTO countrieslu VALUES ('GS', 'South Georgia South Sandwich Islands');
INSERT INTO countrieslu VALUES ('ES', 'Spain');
INSERT INTO countrieslu VALUES ('LK', 'Sri Lanka');
INSERT INTO countrieslu VALUES ('SH', 'St. Helena');
INSERT INTO countrieslu VALUES ('PM', 'St. Pierre and Miquelon');
INSERT INTO countrieslu VALUES ('SD', 'Sudan');
INSERT INTO countrieslu VALUES ('SR', 'Suriname');
INSERT INTO countrieslu VALUES ('SJ', 'Svalbard and Jan Mayen Islands');
INSERT INTO countrieslu VALUES ('SZ', 'Swaziland');
INSERT INTO countrieslu VALUES ('SE', 'Sweden');
INSERT INTO countrieslu VALUES ('CH', 'Switzerland');
INSERT INTO countrieslu VALUES ('SY', 'Syrian Arab Republic');
INSERT INTO countrieslu VALUES ('TW', 'Taiwan');
INSERT INTO countrieslu VALUES ('TJ', 'Tajikistan');
INSERT INTO countrieslu VALUES ('TZ', 'Tanzania, United Republic of');
INSERT INTO countrieslu VALUES ('TH', 'Thailand');
INSERT INTO countrieslu VALUES ('TG', 'Togo');
INSERT INTO countrieslu VALUES ('TK', 'Tokelau');
INSERT INTO countrieslu VALUES ('TO', 'Tonga');
INSERT INTO countrieslu VALUES ('TT', 'Trinidad and Tobago');
INSERT INTO countrieslu VALUES ('TN', 'Tunisia');
INSERT INTO countrieslu VALUES ('TR', 'Turkey');
INSERT INTO countrieslu VALUES ('TM', 'Turkmenistan');
INSERT INTO countrieslu VALUES ('TC', 'Turks and Caicos Islands');
INSERT INTO countrieslu VALUES ('TV', 'Tuvalu');
INSERT INTO countrieslu VALUES ('UG', 'Uganda');
INSERT INTO countrieslu VALUES ('UA', 'Ukraine');
INSERT INTO countrieslu VALUES ('AE', 'United Arab Emirates');
INSERT INTO countrieslu VALUES ('GB', 'United Kingdom');
INSERT INTO countrieslu VALUES ('US', 'United States');
INSERT INTO countrieslu VALUES ('UM', 'United States minor outlying islands');
INSERT INTO countrieslu VALUES ('UY', 'Uruguay');
INSERT INTO countrieslu VALUES ('UZ', 'Uzbekistan');
INSERT INTO countrieslu VALUES ('VU', 'Vanuatu');
INSERT INTO countrieslu VALUES ('VA', 'Vatican City State');
INSERT INTO countrieslu VALUES ('VE', 'Venezuela');
INSERT INTO countrieslu VALUES ('VN', 'Vietnam');
INSERT INTO countrieslu VALUES ('VG', 'Virgin Islands (British)');
INSERT INTO countrieslu VALUES ('VI', 'Virgin Islands (U.S.)');
INSERT INTO countrieslu VALUES ('WF', 'Wallis and Futuna Islands');
INSERT INTO countrieslu VALUES ('EH', 'Western Sahara');
INSERT INTO countrieslu VALUES ('YE', 'Yemen');
INSERT INTO countrieslu VALUES ('YU', 'Yugoslavia');
INSERT INTO countrieslu VALUES ('ZR', 'Zaire');
INSERT INTO countrieslu VALUES ('ZM', 'Zambia');
INSERT INTO countrieslu VALUES ('ZW', 'Zimbabwe');


-- Add data to ProvinceLU table
INSERT INTO provinceslu VALUES ('AB',	'Alberta');
INSERT INTO provinceslu VALUES ('BC',	'British Columbia');
INSERT INTO provinceslu VALUES ('MB',	'Manitoba');
INSERT INTO provinceslu VALUES ('NB',	'New Brunswick');
INSERT INTO provinceslu VALUES ('NL',	'Newfoundland and Labrador');
INSERT INTO provinceslu VALUES ('NS',	'Nova Scotia');
INSERT INTO provinceslu VALUES ('NT',	'Northwest Territories');
INSERT INTO provinceslu VALUES ('NU',	'Nunavut');
INSERT INTO provinceslu VALUES ('ON',	'Ontario');
INSERT INTO provinceslu VALUES ('PE',	'Prince Edward Island');
INSERT INTO provinceslu VALUES ('QC',	'Quebec');
INSERT INTO provinceslu VALUES ('SK',	'Saskatchewan');
INSERT INTO provinceslu VALUES ('YT',	'Yukon');


--Add data to counties lu table
INSERT INTO nscountieslu VALUES(1,	'Annapolis');
INSERT INTO nscountieslu VALUES(2,	'Antigonish');
INSERT INTO nscountieslu VALUES(3,	'Cape Breton');
INSERT INTO nscountieslu VALUES(4,	'Colchester');
INSERT INTO nscountieslu VALUES(5,	'Cumberland');
INSERT INTO nscountieslu VALUES(6,	'Digby'	);
INSERT INTO nscountieslu VALUES(7,	'Guysborough');
INSERT INTO nscountieslu VALUES(8,	'Halifax');
INSERT INTO nscountieslu VALUES(9,	'Hants'	);
INSERT INTO nscountieslu VALUES(10,	'Inverness');
INSERT INTO nscountieslu VALUES(11,	'Kings'	);
INSERT INTO nscountieslu VALUES(12,	'Lunenburg');
INSERT INTO nscountieslu VALUES(13,	'Pictou');
INSERT INTO nscountieslu VALUES(14,	'Queensc');
INSERT INTO nscountieslu VALUES(15,	'Richmond');
INSERT INTO nscountieslu VALUES(16,	'Shelburne');
INSERT INTO nscountieslu VALUES(17,	'Victoria');
INSERT INTO nscountieslu VALUES(18,	'Yarmouth');

--pulled this from the website, formatted to csv and imported into program table
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (1,'Addictions Community Outreach ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (2,'Adult Learning Program (ALP) ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (3,'Aircraft Maintenance Engineer ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (4,'American Sign LanguageEnglish Interpretation ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (5,'Applied Media and Communication Arts ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (6,'Architectural Engineering Technician ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (7,'Automotive Collision Repair and Refinishing ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (8,'Automotive Service and Repair ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (9,'Baking and Pastry Art ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (10,'Behavioural Interventions ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (11,'Boulanger and Baking Art ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (12,'Bricklaying Masonry ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (13,'Bridge Watch Rating ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (14,'Building Systems Technician (HVACandR) ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (15,'Business Administration ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (16,'Cabinetmaking ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (17,'CAD Technician Mechanical ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (18,'Carpentry ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (19,'Child and Youth Care ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (20,'Civil Engineering Technology ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (21,'Community Disability Supports ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (22,'Computer Electronics Technician ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (23,'Construction Management Technology ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (24,'Construction Trades Labour ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (25,'Continuing Care ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (26,'Cooking ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (27,'Cosmetology ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (28,'Criminal Justice ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (29,'Culinary Arts ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (30,'Deaf Studies ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (31,'Dental Assisting ? Level II ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (32,'Diesel Repair ? Industrial and Marine ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (33,'Digital Animation ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (34,'Drafting ? Architectural ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (35,'Early Childhood Education ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (36,'Electrical Construction and Industrial  ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (37,'Electrical Engineering Technology ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (38,'Electrical Technician ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (39,'Electro Mechanical Technician ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (40,'Electronic Engineering Technician ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (41,'Electronic Engineering Technology ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (42,'Energy Sustainability Engineering Technology ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (43,'Engine Room Rating ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (44,'English for Academic Purposes ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (45,'Environmental Engineering Technology ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (46,'Esthetics and Spa Therapies ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (47,'Funeral and Allied Health Services ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (48,'Funeral Arranging and Directing ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (49,'Game Development ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (50,'Gas Technician ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (51,'Geographic Sciences ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (52,'Geomatics Engineering Technology ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (53,'Graphic and Print Production ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (54,'Graphic Design ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (55,'Health Information Management (HIM) ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (56,'Heavy Duty Equipment Truck and Transport Repair ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (57,'Heavy Equipment Operator ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (58,'Heritage Carpentry ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (59,'Horticulture and Landscape Technology ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (60,'Human Resource Management ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (61,'Industrial Engineering Technology ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (62,'Industrial Instrumentation ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (63,'Industrial Mechanical ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (64,'Information Technology (IT) ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (65,'International Business ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (66,'Law and Security ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (67,'Library and Information Technology ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (68,'Machining ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (69,'Marine Engineering Technology');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (70,'Marine Geomatics ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (71,'Marine Industrial Rigging ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (72,'Marine Navigation Technology ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (73,'Mechanical Engineering Technology ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (74,'Medical Laboratory Technology ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (75,'Medical Office Administration ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (76,'Mental Health Recovery and Promotion ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (77,'Metal Fabrication ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (78,'Motorcycle and Power Products Repair ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (79,'Music Arts ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (80,'Music Business ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (81,'Natural Resources Environmental Technology ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (82,'Occupational Health and Safety ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (83,'Occupational Therapy  Physiotherapy Assistant ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (84,'Oceans Resources ? Fisheries and Aquaculture ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (85,'Oceans Technology ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (86,'Office Administration ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (87,'Oil Heat Systems Technician ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (88,'Paralegal Services ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (89,'Pharmacy Technician ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (90,'Photography ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (91,'Pipe Trades ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (92,'Plumbing ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (93,'Power Engineering Technology ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (94,'Practical Nursing ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (95,'Public Relations ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (96,'Radio and Television Arts ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (97,'Recording Arts ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (98,'Recreation for Healthy Communities ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (99,'Refrigeration and Air Conditioning ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (100,'Screen Arts ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (101,'Sheet Metal Worker Pre-Apprenticeship ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (102,'Social Services ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (103,'Steamfitting Pipefitting ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (104,'Survey Technician ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (105,'Therapeutic Recreation ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (106,'Tourism Management ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (107,'Utility Line Work ? Construction and Maintenance ');
INSERT INTO PROGRAM (ID, PROGRAMNAME) VALUES (108,'Welding');


--Create Campus list
Insert into RYAN_DDL.CAMPUS (ID,NAME) values (1,'Akerley');
Insert into RYAN_DDL.CAMPUS (ID,NAME) values (2,'Annapolis Valley');
Insert into RYAN_DDL.CAMPUS (ID,NAME) values (3,'Burridge');
Insert into RYAN_DDL.CAMPUS (ID,NAME) values (4,'Central Office');
Insert into RYAN_DDL.CAMPUS (ID,NAME) values (5,'Cumberland');
Insert into RYAN_DDL.CAMPUS (ID,NAME) values (6,'Institute of Technology');
Insert into RYAN_DDL.CAMPUS (ID,NAME) values (7,'Kingstec');
Insert into RYAN_DDL.CAMPUS (ID,NAME) values (8,'Lunenburg');
Insert into RYAN_DDL.CAMPUS (ID,NAME) values (9,'Marconi');
Insert into RYAN_DDL.CAMPUS (ID,NAME) values (10,'Pictou');
Insert into RYAN_DDL.CAMPUS (ID,NAME) values (11,'Shelburne');
Insert into RYAN_DDL.CAMPUS (ID,NAME) values (12,'Strait Area');
Insert into RYAN_DDL.CAMPUS (ID,NAME) values (13,'Truro');
Insert into RYAN_DDL.CAMPUS (ID,NAME) values (14,'Waterfront');


Insert into RYAN_DDL.CITIZENSHIPLU (ID,NAME) values (1,'Canadian Citizen');
Insert into RYAN_DDL.CITIZENSHIPLU (ID,NAME) values (2,'Permanent Resident (Landed Immigrant');
Insert into RYAN_DDL.CITIZENSHIPLU (ID,NAME) values (3,'Refugee with Protected Person Status ');
Insert into RYAN_DDL.CITIZENSHIPLU (ID,NAME) values (4,'Other');

--Personal Info Table Dummy records
INSERT INTO PERSONALINFO VALUES (NULL,'Ryan','Smith','128456991','',to_date('2/12/1966', 'MM/DD/YYYY'),'M','5','123 Sale Street','Dartmouth',8.0,'NS','CA','B3A2T7','9025557989','5148561233','','','',1.0,'Y','','',9.0,9.0,2.0,3.0,'Y');
INSERT INTO PERSONALINFO VALUES (NULL,'Dave','Rogers','199645789','',to_date('2/19/1996', 'MM/DD/YYYY'),'M','206','95 Ross road','Highville',9.0,'NS','CA','B7W5A2','926455555','7195554545','','blah@rogers.ca','',1.0,'Y','','',55.0,24.0,2.0,3.0,'Y');
INSERT INTO PERSONALINFO VALUES (NULL,'Matt','Bennett','215456987','',to_date('11/12/1992', 'MM/DD/YYYY'),'M','B','2200 Cardigal Street','Cole Harbour',8.0,'NS','CA','B8Y3M6','9025559574','','','bennettmatt123@yuhoo.ca','',1.0,'Y','','',90.0,89.0,3.0,6.0,'Y');
INSERT INTO PERSONALINFO VALUES (NULL,'Cory','McDonald','441986833','',to_date('2/12/2000', 'MM/DD/YYYY'),'M','','63 Joffre Street','Dartmouth',8.0,'NS','CA','B3A2T7','9025559574','','','corymac@rogers.ca','',1.0,'Y','','',2.0,55.0,7.0,11.0,'N');
INSERT INTO PERSONALINFO VALUES (NULL,'Sally','Anne-Murray','191995132','Davidson',to_date('5/23/1994', 'MM/DD/YYYY'),'F','','74 Seaside Lane','Port Hawksbury',3.0,'NS','CA','B7W8I2','902845654','','9028175936','annemurray@yahoo.ca','',1.0,'Y','','',1.0,2.0,14.0,11.0,'N');
INSERT INTO PERSONALINFO VALUES (NULL,'Bob','Yankovic','171045132','',to_date('8/1/1987', 'MM/DD/YYYY'),'M','','202-65 Rue de Calles','Cuenca',NULL,'','EC','','987553645','','','vaerac@gmail.ec','',2.0,'N','EC','Spanish',107.0,3.0,5.0,1.0,'N');
INSERT INTO PERSONALINFO VALUES (NULL,'Craig','Dillinger','129645378','',to_date('8/1/1956', 'MM/DD/YYYY'),'M','','9983 Bridge Street','Lunenburg',4.0,'NS','CA','B7Y8V2','','','','','2005498',1.0,'Y','','',NULL,12.0,3.0,3.0,'Y');
INSERT INTO PERSONALINFO VALUES (NULL,'Devin','Turner','11555777','',to_date('8/23/1988', 'MM/DD/YYYY'),'M','V','45 Spryfield Rd','Spryfield',8.0,'NS','CA','B3RT6A','89754335','','','devinislame@yahoo.ca','',1.0,'Y','','',9.0,10.0,5.0,5.0,'N');
INSERT INTO PERSONALINFO VALUES (NULL,'Rae','Cyrus','111444333','',to_date('9/11/1970', 'MM/DD/YYYY'),'F','','2 Tood Rd','Cambellton',NULL,'NB','CA','E3D6YT','506754456','','','cambus@gomail.com','',1.0,'Y','','',7.0,7.0,5.0,2.0,'N');
INSERT INTO PERSONALINFO VALUES (NULL,'Traverse','Davis','111555888','Davidson',to_date('9/12/1972', 'MM/DD/YYYY'),'M','23','2 Happy Lane','Halifax',8.0,'NS','CA','B3AA3B','9025555555','','9029991111','traversedavis@instructors.net','',1.0,'Y','','',27.0,NULL,2.0,NULL,'N');

